<?php

namespace Container1fCTrwZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NXGjW90Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NXGjW90' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NXGjW90'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'post' => ['privates', '.errored..service_locator.NXGjW90.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.NXGjW90": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'manager' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
