<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRTSc2Jn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRTSc2Jn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRTSc2Jn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRTSc2Jn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRTSc2Jn\App_KernelDevDebugContainer([
    'container.build_hash' => 'RTSc2Jn',
    'container.build_id' => '8ac46c61',
    'container.build_time' => 1649371098,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRTSc2Jn');
