<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1fCTrwZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1fCTrwZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1fCTrwZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1fCTrwZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1fCTrwZ\App_KernelDevDebugContainer([
    'container.build_hash' => '1fCTrwZ',
    'container.build_id' => 'e6fb777f',
    'container.build_time' => 1649018741,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1fCTrwZ');
