<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFPv3OCP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFPv3OCP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFPv3OCP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFPv3OCP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFPv3OCP\App_KernelDevDebugContainer([
    'container.build_hash' => 'FPv3OCP',
    'container.build_id' => 'd9ed02f7',
    'container.build_time' => 1649366585,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFPv3OCP');
